{ pkgs, ... }:

{
  wayland.windowManager.hyprland = {
    enable = pkgs.stdenv.isLinux;
    configType = "hyprlang";
    package = null; # Use system Hyprland on Fedora to avoid downloading redundant GPU/Qt stack
    settings = {
      # Environment variables
      env = [
        "qsConfig,end4-pC"
      ];

      # Source colors dynamically generated by Matugen
      source = [
        "~/.config/hypr/colors.conf"
      ];

      # Monitor configuration
      monitor = [
        ",preferred,auto,1"
      ];

      # Autostart essential services
      exec-once = [
        "dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP PATH"
        "systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP PATH"
        "swaync"
        "wl-paste --watch cliphist store"
      ];

      # Keyboard input configuration (US AltGr International)
      input = {
        kb_layout = "us";
        kb_variant = "altgr-intl";
        follow_mouse = 1;
        touchpad = {
          natural_scroll = true;
        };
      };

      # General layout and borders
      general = {
        gaps_in = 4;
        gaps_out = 8;
        border_size = 2;
        "col.active_border" = "$primary $primary_container 45deg";
        "col.inactive_border" = "$surface_container";
        layout = "dwindle";
        resize_on_border = true;
      };

      # Decoration with rounded corners and subtle blur (Aylur style)
      decoration = {
        rounding = 10;
        active_opacity = 1.0;
        inactive_opacity = 0.92;

        blur = {
          enabled = true;
          size = 6;
          passes = 2;
          new_optimizations = true;
          xray = true;
        };

        shadow = {
          enabled = true;
          range = 20;
          render_power = 3;
          color = "rgba(00000044)";
        };
      };

      # Smooth animations inspired by Aylur's configuration
      animations = {
        enabled = true;

        bezier = [
          "easeOutQuint, 0.23, 1, 0.32, 1"
          "easeInOutCubic, 0.65, 0.05, 0.36, 1"
          "overshoot, 0.05, 0.9, 0.1, 1.05"
        ];

        animation = [
          "windows, 1, 4, easeOutQuint"
          "windowsOut, 1, 3, easeInOutCubic, popin 80%"
          "windowsMove, 1, 4, easeOutQuint"
          "fade, 1, 3, easeInOutCubic"
          "workspaces, 1, 4, easeOutQuint, slide"
        ];
      };

      dwindle = {
        preserve_split = true;
      };

      misc = {
        disable_hyprland_logo = true;
        disable_splash_rendering = true;
      };

      "$mod" = "SUPER";

      # Keybindings
      bind = [
        # Quickshell / illogical-impulse global shortcuts
        "$mod, SUPER_L, global, quickshell:searchToggleRelease"
        "$mod, Tab, global, quickshell:overviewWorkspacesToggle"
        "$mod, V, global, quickshell:overviewClipboardToggle"
        "$mod, Period, global, quickshell:overviewEmojiToggle"
        "$mod, A, global, quickshell:sidebarLeftToggle"
        "$mod ALT, A, global, quickshell:sidebarLeftToggleDetach"
        "$mod, N, global, quickshell:sidebarRightToggle"
        "$mod, Slash, global, quickshell:cheatsheetToggle"
        "$mod, K, global, quickshell:oskToggle"
        "$mod, M, global, quickshell:mediaControlsToggle"
        "$mod, G, global, quickshell:overlayToggle"
        "$mod, B, global, quickshell:barToggle"
        "CTRL $mod, T, global, quickshell:wallpaperSelectorToggle"
        "CTRL $mod ALT, T, global, quickshell:wallpaperSelectorRandom"
        "CTRL $mod SHIFT, D, global, quickshell:toggleLightDark"
        "$mod SHIFT, S, global, quickshell:regionScreenshot"
        "$mod SHIFT, A, global, quickshell:regionSearch"
        "$mod SHIFT, X, global, quickshell:regionOcr"
        "$mod SHIFT, T, global, quickshell:screenTranslate"
        "$mod SHIFT, C, exec, hyprpicker -a"
        "$mod SHIFT, R, global, quickshell:regionRecord"
        "CTRL ALT, Delete, global, quickshell:sessionToggle"

        # Application launchers
        "$mod, RETURN, exec, alacritty"
        "$mod SHIFT, RETURN, exec, kitty"
        "$mod, E, exec, nautilus"
        "$mod, D, exec, rofi -show drun || wofi --show drun"

        # Window management
        "$mod, Q, killactive,"
        "$mod, F, fullscreen, 0"
        "$mod, T, togglefloating,"
        "$mod, J, layoutmsg, togglesplit"

        # Navigation / Focus
        "$mod, left, movefocus, l"
        "$mod, right, movefocus, r"
        "$mod, up, movefocus, u"
        "$mod, down, movefocus, d"
        "$mod, H, movefocus, l"
        "$mod, L, movefocus, r"
        "$mod, K, movefocus, u"

        # Window swap
        "$mod SHIFT, left, swapwindow, l"
        "$mod SHIFT, right, swapwindow, r"
        "$mod SHIFT, up, swapwindow, u"
        "$mod SHIFT, down, swapwindow, d"
        "$mod SHIFT, H, swapwindow, l"
        "$mod SHIFT, L, swapwindow, r"
        "$mod SHIFT, K, swapwindow, u"
        "$mod SHIFT, J, swapwindow, d"

        # Workspaces 1-10
        "$mod, 1, workspace, 1"
        "$mod, 2, workspace, 2"
        "$mod, 3, workspace, 3"
        "$mod, 4, workspace, 4"
        "$mod, 5, workspace, 5"
        "$mod, 6, workspace, 6"
        "$mod, 7, workspace, 7"
        "$mod, 8, workspace, 8"
        "$mod, 9, workspace, 9"
        "$mod, 0, workspace, 10"

        # Move active window to workspace 1-10
        "$mod SHIFT, 1, movetoworkspace, 1"
        "$mod SHIFT, 2, movetoworkspace, 2"
        "$mod SHIFT, 3, movetoworkspace, 3"
        "$mod SHIFT, 4, movetoworkspace, 4"
        "$mod SHIFT, 5, movetoworkspace, 5"
        "$mod SHIFT, 6, movetoworkspace, 6"
        "$mod SHIFT, 7, movetoworkspace, 7"
        "$mod SHIFT, 8, movetoworkspace, 8"
        "$mod SHIFT, 9, movetoworkspace, 9"
        "$mod SHIFT, 0, movetoworkspace, 10"

        # Screenshot keybindings
        ", Print, exec, hypr-screenshot area"
        "SHIFT, Print, exec, hypr-screenshot full"
        "$mod, Print, exec, hypr-screenshot window"
        "$mod ALT, S, exec, hypr-screenshot window"
      ];

      # Mouse bindings
      bindm = [
        "$mod, mouse:272, movewindow"
        "$mod, mouse:273, resizewindow"
      ];

      # Repeating hardware keys (volume, brightness)
      bindel = [
        ", XF86AudioRaiseVolume, exec, wpctl set-volume -l 1.5 @DEFAULT_AUDIO_SINK@ 5%+"
        ", XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"
        ", XF86MonBrightnessUp, exec, brightnessctl set +5%"
        ", XF86MonBrightnessDown, exec, brightnessctl set 5%-"
      ];

      # Locked media keys (mute, mic, playback)
      bindl = [
        ", XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"
        ", XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"
        ", XF86AudioPlay, exec, playerctl play-pause"
        ", XF86AudioNext, exec, playerctl next"
        ", XF86AudioPrev, exec, playerctl previous"
      ];
    };
  };

  xdg.portal = {
    enable = pkgs.stdenv.isLinux;
    config = {
      common.default = "*";
      hyprland.default = [ "hyprland" "gtk" ];
    };
  };

  home.packages = let
    hyprAutostart = pkgs.writeShellScriptBin "hypr-autostart" ''
      #!/usr/bin/env bash
      dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP PATH
      systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP PATH

      if [ -f "$HOME/.config/hypr/current_wallpaper" ]; then
        pkill -9 swaybg 2>/dev/null || true
        swaybg -i "$(cat "$HOME/.config/hypr/current_wallpaper")" -m fill &
      fi

      pkill -9 qs 2>/dev/null || true
      sleep 0.1
      qs -c end4-pC &

      pgrep -x swaync >/dev/null || swaync &
      pgrep -x wl-paste >/dev/null || wl-paste --watch cliphist store &
    '';

    hyprScreenshot = pkgs.writeShellScriptBin "hypr-screenshot" ''
      #!/usr/bin/env bash
      DIR="$HOME/Pictures/Screenshots"
      [ -d "$HOME/Imágenes" ] && DIR="$HOME/Imágenes/Screenshots"
      mkdir -p "$DIR"

      FILENAME="$DIR/screenshot_$(date +'%Y%m%d_%H%M%S').png"
      MODE="''${1:-area}"

      case "$MODE" in
        area)
          GEOM=$(${pkgs.slurp}/bin/slurp 2>/dev/null)
          [ -z "$GEOM" ] && exit 0
          ${pkgs.grim}/bin/grim -g "$GEOM" "$FILENAME"
          ;;
        full)
          ${pkgs.grim}/bin/grim "$FILENAME"
          ;;
        window)
          ACTIVE_WINDOW=$(hyprctl activewindow -j 2>/dev/null)
          AT=$(echo "$ACTIVE_WINDOW" | ${pkgs.jq}/bin/jq -r '.at | "\(.[0]),\(.[1])"' 2>/dev/null)
          SIZE=$(echo "$ACTIVE_WINDOW" | ${pkgs.jq}/bin/jq -r '.size | "\(.[0])x\(.[1])"' 2>/dev/null)
          if [ -n "$AT" ] && [ -n "$SIZE" ] && [ "$AT" != "null" ]; then
            ${pkgs.grim}/bin/grim -g "''${AT} ''${SIZE}" "$FILENAME"
          else
            ${pkgs.grim}/bin/grim "$FILENAME"
          fi
          ;;
        *)
          ${pkgs.grim}/bin/grim "$FILENAME"
          ;;
      esac

      if [ -f "$FILENAME" ]; then
        ${pkgs.wl-clipboard}/bin/wl-copy < "$FILENAME"
        notify-send -a "Screenshot" "Captura guardada" "Copiada al portapapeles y guardada en:\n$FILENAME" -i "$FILENAME" 2>/dev/null || true
      fi
    '';
  in [
    hyprAutostart
    hyprScreenshot
    pkgs.grim
    pkgs.slurp
    pkgs.wl-clipboard
    pkgs.jq
    pkgs.brightnessctl
    pkgs.playerctl
  ];

  home.file = {
    ".config/hypr/hyprland.lua".source = ./hyprland/hyprland.lua;
  };
}
