[config]
reload_apps = true

[templates.hyprland_conf]
input_path = "~/.config/matugen/templates/hyprland-colors.conf"
output_path = "~/.config/hypr/colors.conf"
post_hook = "hyprctl reload 2>/dev/null || true"

[templates.hyprland_lua]
input_path = "~/.config/matugen/templates/hyprland-colors.lua"
output_path = "~/.config/hypr/colors.lua"
post_hook = "hyprctl reload 2>/dev/null || true"


[templates.alacritty]
input_path = "~/.config/matugen/templates/alacritty-colors.toml"
output_path = "~/.config/alacritty/colors.toml"

[templates.kitty]
input_path = "~/.config/matugen/templates/kitty-colors.conf"
output_path = "~/.config/kitty/colors.conf"
